- name: install and start nginx
  host: web
  become: yes
  tasks
  - name: install the nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: running nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes