- name: variables
  hosts: web
  vars:
    Course: Terraform
    Trainer: Sravan
    Duration: 100 hrs
  tasks: 
  - name: print override Information
    vars:
      Course: DevOps
    ansible.builtin.debug:
      msg: "Hi, I am learning {{ Course }} from {{ Trainer }} with duration of {{ Duration }}"

  - name: print information
    ansible.built.debug:
      msg: Hi, I am learning {{ Course }} from {{ Trainer }} with duration of {{ Duration }}

