- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
    ansiblie.builtin.debug:
      msg: " Hi, I am learning {{ Course }} from rainer {{ Trainer }} with duration of {{ Duration }}"