- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
    ansibile.builtin.debug:
      msg: " Hi, I am learning {{ Course }} from trainer {{ Trainer }} with duration of {{ Duration }}"