- name: Variables 
  hosts: web
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "Hi, I am learning course {{ Course }} from trainer {{ Trainer }} with duration of {{ Duration }}"
