- name: variable preferences
  hosts:  localhost
  vars: WISHES
    WISHES: Good Morning from PLAY Level
 vars_prompt:
  - name: WISHES
    prompt: Please enter your wishes
    private: no
  tasks: 
  - name: check preference
    vars:
      WISHES: "Morning from TASK Level"
    ansible.builtin.debug:
      msg: " Hello, Good {{ WISHES }} "
